-- require('colorizer').setup({RRGGBB = true, mode = 'background'})
-- require('colorizer').setup(nil, { RRGGBB = true; mode = 'background' })

-- RGB      = true,         -- #Rgb hex codes
-- RRGGBB   = true,         -- #RRGGBB hex codes
-- names    = true,         -- "Name" codes like Blue
-- rgb_fn   = false,        -- CSS rgb() and rgba() functions
-- hsl_fn   = false,        -- CSS hsl() and hsla() functions
-- css      = false,        -- Enable all CSS features: rgb_fn, hsl_fn, names, RGB, RRGGBB
-- css_fn   = false,        -- Enable all CSS *functions*: rgb_fn, hsl_fn
-- -- Available modes: foreground, background
-- mode     = 'background'
