---
exclude: "^$"
fail_fast: false
default_stages: ['commit']
minimum_pre_commit_version: 2.9.3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=60000']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: ['--fix=auto']
      - id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md']
        exclude_types: ['yaml']
      - id: end-of-file-fixer
      - id: pretty-format-json
        args: ['--autofix']
      - id: requirements-txt-fixer

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.0
    hooks:
      - id: yamllint

  - repo: local
    hooks:
      - id: talisman-precommit
        name: talisman
        entry: bash -c 'if [ -n "${TALISMAN_HOME:-}" ]; then ${TALISMAN_HOME}/talisman_hook_script pre-commit; else echo "TALISMAN does not exist. Consider installing from https://github.com/thoughtworks/talisman . If you already have talisman installed, please ensure TALISMAN_HOME variable is set to where talisman_hook_script resides, for example, TALISMAN_HOME=${HOME}/.talisman/bin"; fi'
        language: system
        pass_filenames: false
        types: ['text']
        verbose: true
